name: Provinces
version: ${project.version}
main: net.skydistrict.provinces.Provinces
api-version: 1.16
depend: [ Indigo, ProtectionStones, WorldGuard, WorldEdit ]
authors: [ Grabsky ]
commands:
  province:
    aliases: ['teren', 'claim']
    permission: 'skydistrict.province'
    permission-message: 'Insufficient permissions.'