name: ClaimsGUI
version: ${project.version}
main: net.skydistrict.claimsgui.ClaimsGUI
api-version: 1.16
depend: [ Indigo, ProtectionStones, WorldGuard, WorldEdit ]
authors: [ Grabsky ]
commands:
  claim:
    aliases: ['teren', 'claims']
    permission: 'skydistrict.claim'
    permission-message: 'Insufficient permissions.'