name: Claims
version: ${project.version}
main: net.skydistrict.claims.Claims
api-version: 1.16
depend: [ Indigo, WorldGuard, WorldEdit ]
authors: [ Grabsky ]
commands:
  claim:
    aliases: ['teren', 'claims']
    permission: 'skydistrict.claims'
    permission-message: '§6§lS§e§lD§8 » §cBrak uprawnień.'