name: Claims
version: ${project.version}
main: me.grabsky.claims.Claims
api-version: 1.16
depend: [Indigo, WorldEdit, WorldGuard]
softdepend: [Vanish]
authors: [Grabsky]
permissions:
  skydistrict.plugin.claims.*:
    description: 'Difficult to describe; related to plugin behaviour'
    children:
      skydistrict.plugin.claims.place: false
      skydistrict.plugin.claims.destroy: false
      skydistrict.plugin.claims.showall: false
  skydistrict.command.claims.*:
    description: 'Access all claims commands'
    childern:
      skydistrict.command.claims: false
      skydistrict.command.claims.fix: false
      skydistrict.command.claims.others: false
      skydistrict.command.claims.reload: false
  skydistrict.bypass.claims.*:
    description: 'Bypass certain claims actions'
    childern:
      skydistrict.bypass.claims.ownercheck: false
      skydistrict.bypass.claims.teleportdelay: false
      skydistrict.bypass.claims.upgradecost: false