name: Claims
version: ${project.version}
main: me.grabsky.claims.Claims
api-version: 1.16
depend: [Indigo, WorldEdit, WorldGuard]
softdepend: [Vanish]
authors: [Grabsky]
permissions:
  claims.plugin.claims.*:
    children:
      claims.plugin.place: false
      claims.plugin.destroy: false
      claims.plugin.showall: false

  claims.command.claims.*:
    childern:
      claims.command.claims: false
      claims.command.claims.fix: false
      claims.command.claims.others: false
      claims.command.claims.reload: false

  claims.bypass.claims.*:
    childern:
      claims.bypass.ownercheck: false
      claims.bypass.teleportdelay: false
      claims.bypass.upgradecost: false