name: Build (Auto)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Java 21
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      # Setup Gradle
      - name: Gradle
        uses: gradle/actions/setup-gradle@v4
      # Build
      - name: Build
        run: ./gradlew clean shadowJar --no-daemon
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs
