name: Gradle CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checking up
      - uses: actions/checkout@v4
      # Setting up Java 21
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Building
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean shadowJar
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Uploading artifact(s)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs
      # Expose Release Name
      - name: Expose Release Name
        run: echo "PROJECT_RELEASE_NAME=$( ./gradlew release -q --no-rebuild )" >> $GITHUB_ENV
      # Expose Tag
      - name: Expose Tag
        run: echo "PROJECT_TAG=$( ./gradlew tag -q --no-rebuild )" >> $GITHUB_ENV
      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ env.PROJECT_RELEASE_NAME }}"
          tag-name: "${{ env.PROJECT_TAG }}"
          files: 'build/libs/Claims-*.jar'