name: Gradle CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checking up
      - uses: actions/checkout@v3
      # Setting up Java 21
      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      # Building
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Uploading artifact(s)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/libs
      # Expose Release Name
      - name: Expose Release Name
        run: echo "PROJECT_RELEASE_NAME=$( ./gradlew release -q --no-rebuild )" >> $GITHUB_ENV
      # Expose Tag
      - name: Expose Tag
        run: echo "PROJECT_TAG=$( ./gradlew tag -q --no-rebuild )" >> $GITHUB_ENV
      # Release
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.PROJECT_RELEASE_NAME }}"
          tag: "${{ env.PROJECT_TAG }}"